name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis-rejson:
        image: redislabs/rejson:1.0.8
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2
      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.17.0'
        id: go
      - run: "go vet ./..."
      - name: go test
        run: |
          go test -race -v -covermode=atomic -coverprofile=profile.cov ./...
      - name: send coverage to Coveralls
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          GO111MODULE=off go get -u github.com/mattn/goveralls
          $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github
